# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_biopage_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biopage',
            name='zipFile',
            field=models.FileField(upload_to='biopages'),
        ),
    ]
