# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160825_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biopage',
            name='zipFile',
        ),
        migrations.AddField(
            model_name='biopage',
            name='link',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
