# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_project_projectownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectType',
            field=models.IntegerField(choices=[(1, 'Class Project'), (2, 'Code Legion Project'), (3, 'Individual Project')], default=1),
            preserve_default=False,
        ),
    ]
