# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_project_projecttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='', upload_to='/studentImages/'),
            preserve_default=False,
        ),
    ]
