# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to='studentImages/'),
        ),
    ]
