# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20160906_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='', upload_to='/projectImages/'),
            preserve_default=False,
        ),
    ]
